Reorganisation
EGI-Foundation/documentation pull request #70
Opened 2020-10-02 14:00 UTC by enolfc

# Summary 

Move things around to match the discussion on how we should organise the docs

----

**Related issue :**

2020-10-02 14:03 UTC, enolfc commented
Missing the CODEOWNERS... getting there

2020-10-02 14:07 UTC, gwarf requested changes
Great!
From a first check:
* remove the GitHub section, it should go under About as contributing, cf the doc
* split HTC over multiple pages

2020-10-02 14:08 UTC, gwarf commented
Maybe also better to remove the generic text from docsy like on http://localhost:1313/users/

2020-10-02 14:10 UTC, enolfc commented
> Maybe also better to remove the generic text from docsy like on http://localhost:1313/users/ or http://localhost:1313/users/getting-support/

but still leave the placeholder?

2020-10-02 14:13 UTC, gwarf commented
Either add some initial short text (better) or keep the placeholder (acceptable I would say)

2020-10-02 14:29 UTC, andrea-manzi approved these changes
All good from my side!

2020-10-02 14:58 UTC, gwarf submitted a review, later dismissed

2020-10-02 15:20 UTC, andrea-manzi commented on CODEOWNERS
> +# Data Transfer
```suggestion
# Online Storage
```

2020-10-05 07:51 UTC, gwarf approved these changes
LGTM, thanks!

2020-10-05 07:52 UTC, andrea-manzi approved these changes
Good for me

2020-10-05 08:12 UTC, merged