HTC documentation review
EGI-Foundation/documentation pull request #83
Opened 2020-10-13 13:22 UTC by andrea-manzi

# Summary 
Review of the HTC documentation

----

**Related issue :**

2020-10-13 13:24 UTC, gwarf commented on content/en/users/htc/_index.md
> +  in the EGI infrastructure are  [HTCondor-CE](https://htcondor-ce.readthedocs.io/en/latest/)
```suggestion
  in the EGI infrastructure are [HTCondor-CE](https://htcondor-ce.readthedocs.io/en/latest/) 
```

2020-10-13 13:25 UTC, gwarf commented on content/en/users/htc/_index.md
> +  in the EGI infrastructure are  [HTCondor-CE](https://htcondor-ce.readthedocs.io/en/latest/)
Sorry, I've got a problem with double/multiple spaces :)

2020-10-13 13:29 UTC, andrea-manzi commented on content/en/users/htc/_index.md
> +theinfrastructure, the user can collect the output from the services that have
```suggestion
the infrastructure, the user can collect the output from the services that have
```

2020-10-13 13:38 UTC, enolfc reviewed
Now that you are touching this, should we move to high-throughput-compute instead of htc?

2020-10-13 15:50 UTC, CatalinCondurache approved these changes
It looks fine.

2020-10-14 08:21 UTC, andrea-manzi commented
i just renamed the folder

2020-10-14 08:32 UTC, gwarf approved these changes
LGTM

2020-10-14 08:34 UTC, gwarf commented
Hi @CatalinCondurache so it's on you to give the final review, thanks!
Reviews are currently voided when there are new changes, it's something we could also choose to change to ease validating changes by others, if people agree.

2020-10-14 08:42 UTC, gwarf commented
> Reviews are currently voided when there are new changes

I've switched off the option that dismiss pull request reviews when new commits are pushed. It will be on us to decide if it's worth to ask for a formal re-review or if changes have just been addressed and PR can be merged.
It should add some more flexibility and avoid asking for a re-review for a trivial fix.

2020-10-14 09:08 UTC, enolfc requested changes
I know I'm a PITA, but now we need to change the CODEOWNERS file...

2020-10-14 09:20 UTC, gwarf commented
It seems there are also some `.DS_Store` files, that needs to be cleaned. Also worth to be added to the `.gitignore`.
What should be changed for the `CODEOWNERS` ?

2020-10-14 09:26 UTC, enolfc commented
> What should be changed for the `CODEOWNERS` ?

htc -> high-throughput-compute

2020-10-14 10:44 UTC, andrea-manzi commented
should be ok now

2020-10-14 10:45 UTC, enolfc approved these changes
💯

2020-10-16 08:01 UTC, CatalinCondurache approved these changes
OK for now, although I believe we were thinking to be more consistent on using 'High-Throughput Compute' against 'HTC' everywhere in docs.

2020-10-16 08:11 UTC, gwarf commented
@andrea-manzi would you want to replace things like the `EGI HTC` by `EGI High Throughput Compute`?
Indeed it probably makes more sense to use the expanded service name, while for the technology/concept itself HTC could be fine.

2020-10-16 08:33 UTC, andrea-manzi commented
sure going to update the text

2020-10-16 09:00 UTC, gwarf commented
Thanks!
I feel it's good enough to be merged, but I wonder if in the future we should try to have an habit to point to the service page like
```markdown
[EGI High Throughput Compute](https://www.egi.eu/services/high-throughput-compute/)
```
Opinions?

2020-10-16 09:14 UTC, merged